name: tradenote
services:
  tradenote:
    image: eleventrading/tradenote
    container_name: tradenote_app
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      MONGO_URI: ${MONGO_URI}
      TRADENOTE_DATABASE: ${TRADENOTE_DATABASE}
      APP_ID: ${APP_ID}
      MASTER_KEY: ${MASTER_KEY}
      TRADENOTE_PORT: ${TRADENOTE_PORT}
